# Generated by Django 3.2.9 on 2022-05-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=20)),
                ('chip', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('video_memory', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amount', models.FloatField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('rub_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.rub', verbose_name='Тип Видеокарты')),
            ],
            options={
                'verbose_name': 'ВидеоКарта',
                'verbose_name_plural': 'ВидеоКарты',
            },
        ),
    ]
