# Generated by Django 3.2.9 on 2022-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rub',
            options={'ordering': ['id'], 'verbose_name': 'Категория'},
        ),
        migrations.AddField(
            model_name='rub',
            name='slug_field',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='videocard',
            name='slug',
            field=models.SlugField(max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='price',
            field=models.FloatField(),
        ),
    ]
