# Generated by Django 3.2.9 on 2022-06-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220626_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rub',
            options={'verbose_name': 'Категория'},
        ),
    ]
