# Generated by Django 3.2.9 on 2022-07-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_rub_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rub',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
