# Generated by Django 3.2.9 on 2022-07-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='videocard',
            options={'verbose_name': 'ВидеоКарта', 'verbose_name_plural': 'Видеокарты'},
        ),
        migrations.AlterIndexTogether(
            name='videocard',
            index_together={('id', 'slug')},
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
