# Generated by Django 3.2.9 on 2022-08-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220717_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
